version: '3'

services:
  backend:
    build: backend/
    restart: unless-stopped
    ports:
      - 8000:8000

  frontend:
    build: frontend/paperless/
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 8003:80