version: "3.8"
services:
  frontend:
    image: paperless:nginx
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"

  backend:
    image: paperless:openjdk
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - db

  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: paperless_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
