version: "3.8"
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"

  backend:
    image: paperless:openjdk
    build:
      dockerfile: Dockerfile
    ports:
      - "8088:8088"

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: paperless
      POSTGRES_DB: paperless-swkom
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - paperless-data:/var/lib/postgresql/data

volumes:
  paperless-data:
